### ISSUE TITLE
Contract Whitelist is not working

### ISSUE THREAD

**Issue by gyroflaw** [casper-ecosystem/cep-78-enhanced-nft#82]
I tried to mint about 2000 NFTs and since there is such a mint_multiple entry point, I wrote a smart contract that repeatedly calls the `mint` entry point.
And I found that contract_whitelist doesn't store the list I provided on the contract install deployment.
(IMO, Vec<ContractHash> may be a issue)
Here are the deployment links.
Contract deploy: https://testnet.cspr.live/deploy/80b5041d1a9e97ab86f839f414ddc7adb65653ca51c1dbb1e31348e95f1b73a4
Mint multiple: https://testnet.cspr.live/deploy/c57d2470bf03f256b9016c017723ed6770936601d00054c85bea2dcd6895a081

**Comment by RitaMAllenCA** [comment]
@darthsiroftardis need an estimate

**Comment by RitaMAllenCA** [comment]
@darthsiroftardis marking this for the sprint for visibility only.   Based on discussions, I suspect this is one of the "nice to haves" in the SDK but since Ryo wrote it, it could be a good candidate for the sprint?  THoughts?

**Comment by RitaMAllenCA** [comment]
Hey @gyroflaw I’m using Zenhub in GitHub, [click this link](https://app.zenhub.com/workspaces/engineering-l2-62618a6423afe100128e4656/board) to join my workspace and see other features available in GitHub or [download the Zenhub extension](https://www.zenhub.com/extension) and sign up with your GitHub account.
  _Posted using [Zenhub](https://www.zenhub.com)_

**Comment by deuszex** [comment]
Deployment links are nice and all, but where is the session code used? Also almost 3 months old. Is this "bug" still live and recreatable?

**Comment by RitaMAllenCA** [comment]
won't do - whitelist is working
